{ config, lib, ... }:
{ imports = [

./github/data_repository.nix
./github/resource_repository_collaborator.nix
./github/resource_team_membership.nix
./github/resource_project_column.nix
./github/resource_repository.nix
./github/data_repositories.nix
./github/resource_organization_project.nix
./github/resource_organization_webhook.nix
./github/resource_issue_label.nix
./github/resource_user_ssh_key.nix
./github/resource_repository_deploy_key.nix
./github/resource_team.nix
./github/resource_membership.nix
./github/resource_branch_protection.nix
./github/resource_repository_webhook.nix
./github/resource_team_repository.nix
./github/resource_user_gpg_key.nix
./github/resource_repository_project.nix
./github/resource_user_invitation_accepter.nix
./hcloud/resource_floating_ip.nix
./hcloud/data_floating_ip.nix
./hcloud/resource_server.nix
./hcloud/resource_volume.nix
./hcloud/resource_volume_attachment.nix
./hcloud/data_ssh_key.nix
./hcloud/data_image.nix
./hcloud/resource_rdns.nix
./hcloud/data_volume.nix
./hcloud/resource_ssh_key.nix
./hcloud/resource_floating_ip_assignment.nix
./cloudflare/resource_worker_script.nix
./cloudflare/resource_load_balancer.nix
./cloudflare/resource_record.nix
./cloudflare/resource_access_policy.nix
./cloudflare/resource_worker_route.nix
./cloudflare/resource_zone_lockdown.nix
./cloudflare/resource_page_rule.nix
./cloudflare/resource_access_application.nix
./cloudflare/resource_zone.nix
./cloudflare/resource_waf_rule.nix
./cloudflare/resource_custom_pages.nix
./cloudflare/resource_rate_limit.nix
./cloudflare/resource_access_rule.nix
./cloudflare/resource_load_balancer_pool.nix
./cloudflare/resource_account_member.nix
./cloudflare/resource_firewall_rule.nix
./cloudflare/resource_filter.nix
./cloudflare/resource_load_balancer_monitor.nix
./cloudflare/resource_zone_settings_override.nix

];}
